on:
  issues:
    types: [opened]

jobs:
  bookmarks-in-issues:
    runs-on: ubuntu-latest
    steps:
        - uses: hxrxchang/bookmarks-in-issues@v0.0.11
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            url: ${{ github.event.issue.title }}
            number: ${{ github.event.issue.number }}

